- name: Install zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Ensure zsh XDG config dir globally
  lineinfile:
    path: /etc/zsh/zshenv
    line: export ZDOTDIR="${XDG_CONFIG_HOME:-${HOME}/.config}/zsh"
  become: true

- name: Ensure zsh config dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ xdg_config_home }}/zsh/themes"
    - "{{ xdg_config_home }}/zsh/functions"
    - "{{ xdg_config_home }}/zsh/plugins"
    - "{{ xdg_config_home }}/zsh/.zsh.d"
    - "{{ xdg_data_home }}/zsh"
    - "{{ xdg_cache_home }}/zsh"

- name: Ensure zsh default files
  copy:
    src: "{{ item.file }}"
    dest: "{{ xdg_config_home }}/zsh/{{ item.subdir }}{{ item.file }}"
  loop: "{{ files }}"

- name: Ensure pure theme
  git:
    repo: git@github.com:adrianord/pure.git
    dest: "{{ xdg_config_home }}/zsh/themes/pure"
    accept_hostkey: true
    key_file: "{{ user_home }}/.ssh/id_ed25519"

- name: Clone enabled plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ xdg_config_home }}/zsh/plugins/{{ item.name }}"
  loop: "{{ plugins }}"
  when: "item.name is defined and item.repo is defined and item.enabled"

- name: Remove disabled plugins
  file:
    path: "{{ xdg_config_home }}/zsh/plugins/{{ item.name }}"
    state: absent
  loop: "{{ plugins }}"
  when: "item.name is defined and not item.enabled"

- name: Ensure plugins are enabled
  template:
    src: plugins.zsh.j2
    dest: "{{ xdg_config_home }}/zsh/.zsh.d/plugins.zsh"

- name: Set user shell
  user:
    name: "{{ username }}"
    shell: "/usr/bin/zsh"
  become: true
