---
- include: deb.yaml
  when: |
    ansible_distribution == 'Debian' 
    or ansible_distribution == 'Ubuntu' 
    or ansible_distribution == 'Pop!_OS' 
 
- name: Symlink neovim configuration
  file:
    src: "{{role_path}}/files"
    dest: "{{xdg_config_home}}/nvim"
    state: link

