- name: Ensure config dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ xdg_config_home }}/nvim"
    - "{{ xdg_config_home }}/nvim/vscode"
    - "{{ xdg_config_home }}/nvim/vim"
    - "{{ xdg_config_home }}/nvim/shared"
