- name: Ensure config dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ xdg_config_home }}/nvim"
    - "{{ xdg_config_home }}/nvim/vscode"
    - "{{ xdg_config_home }}/nvim/vim"
    - "{{ xdg_config_home }}/nvim/shared"

- name: Copy directories
  copy:
    src: "{{ item }}"
    dest: "{{ xdg_config_home }}/nvim/{{ item }}"
  loop:
    - vim/
    - shared/

- name: Ensure init.vim
  copy:
    src: init.vim
    dest: "{{ xdg_config_home }}/nvim/init.vim"
